
overlay use numd/commands.nu --prefix as 'c'

dotnu parse-docstrings numd/commands.nu | to md --pretty | print $in

#: | command_name                        | command_description                                                                                                                                                                                                                                                                                                                 | examples                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | input                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
#: | ----------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
#: | run                                 | Run Nushell code blocks in a markdown file, output results back to the `.md`, and optionally to terminal                                                                                                                                                                                                                            | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Run Nushell code blocks in a markdown file, output results back to the `.md`, and optionally to terminal
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
#: | clear-outputs                       | Remove numd execution outputs from the file                                                                                                                                                                                                                                                                                         | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Remove numd execution outputs from the file
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
#: | capture start                       | start capturing commands and their outputs into a file                                                                                                                                                                                                                                                                              | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # start capturing commands and their outputs into a file
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
#: | capture stop                        | stop capturing commands and their outputs                                                                                                                                                                                                                                                                                           | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # stop capturing commands and their outputs
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
#: | parse-help                          | Beautify and adapt the standard `--help` for markdown output                                                                                                                                                                                                                                                                        | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Beautify and adapt the standard `--help` for markdown output
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
#: | find-code-blocks                    | Detect code blocks in a markdown string and return a table with their line numbers and info strings.                                                                                                                                                                                                                                | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Detect code blocks in a markdown string and return a table with their line numbers and info strings.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
#: | match-action                        |                                                                                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | create-execution-code               | Generate code for execution in the intermediate script within a given code fence.                                                                                                                                                                                                                                                   | [{annotation: , command: > 'ls | sort-by modified -r' | create-execution-code --whole_block ['indent-output'] | save z_examples/999_numd_internals/create-execution-code_0.nu -f, result: }]                                                                                                                                                                                                                                                                                                                                                                           | # Generate code for execution in the intermediate script within a given code fence.
#: #
#: # > 'ls | sort-by modified -r' | create-execution-code --whole_block ['indent-output'] | save z_examples/999_numd_internals/create-execution-code_0.nu -f
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | decortate-original-code-blocks      | generates additional service code necessary for execution and capturing results, while preserving the original code.                                                                                                                                                                                                                | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # generates additional service code necessary for execution and capturing results, while preserving the original code.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
#: | generate-intermediate-script        | Generate an intermediate script from a table of classified markdown code blocks.                                                                                                                                                                                                                                                    | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Generate an intermediate script from a table of classified markdown code blocks.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
#: | execute-block-lines                 |                                                                                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | extract-block-index                 | Parse block indices from Nushell output lines and return a table with the original markdown line numbers.                                                                                                                                                                                                                           | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Parse block indices from Nushell output lines and return a table with the original markdown line numbers.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
#: | merge-markdown                      | Assemble the final markdown by merging the original classified markdown with parsed results of the generated script.                                                                                                                                                                                                                | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Assemble the final markdown by merging the original classified markdown with parsed results of the generated script.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
#: | clean-markdown                      | Prettify markdown by removing unnecessary empty lines and trailing spaces.                                                                                                                                                                                                                                                          | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Prettify markdown by removing unnecessary empty lines and trailing spaces.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#: | toggle-output-fences                | Replacement is needed to distinguish the blocks with outputs from blocks with just ```.
#: `find-code-blocks` works only with lines without knowing the previous lines.                                                                                                                                                                | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Replacement is needed to distinguish the blocks with outputs from blocks with just ```.
#: # `find-code-blocks` works only with lines without knowing the previous lines.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
#: | compute-change-stats                | Calculate changes between the original and updated markdown files and return a record with the differences.                                                                                                                                                                                                                         | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Calculate changes between the original and updated markdown files and return a record with the differences.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
#: | list-code-options                   | List code block options for execution and output customization.                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # List code block options for execution and output customization.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#: | convert-short-options               | Expand short options for code block execution to their long forms.                                                                                                                                                                                                                                                                  | [{annotation: , command: > convert-short-options 'i', result: indent-output}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | # Expand short options for code block execution to their long forms.
#: #
#: # > convert-short-options 'i'
#: # indent-output
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
#: | escape-special-characters-and-quote | Escape symbols to be printed unchanged inside a `print "something"` statement.                                                                                                                                                                                                                                                      | [{annotation: , command: > 'abcd"dfdaf" "' | escape-special-characters-and-quote, result: "abcd\"dfdaf\" \""}]                                                                                                                                                                                                                                                                                                                                                                                                                                                         | # Escape symbols to be printed unchanged inside a `print "something"` statement.
#: #
#: # > 'abcd"dfdaf" "' | escape-special-characters-and-quote
#: # "abcd\"dfdaf\" \""
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#: | execute-intermediate-script         | Run the intermediate script and return its output lines as a list.                                                                                                                                                                                                                                                                  | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Run the intermediate script and return its output lines as a list.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
#: | mark-code-block                     | Generate a unique identifier for code blocks in markdown to distinguish their output.                                                                                                                                                                                                                                               | [{annotation: , command: > mark-code-block 3, result: #code-block-marker-open-3}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | # Generate a unique identifier for code blocks in markdown to distinguish their output.
#: #
#: # > mark-code-block 3
#: # #code-block-marker-open-3
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
#: | create-highlight-command            |                                                                                                                                                                                                                                                                                                                                     | [{annotation: Generate a command to highlight code using Nushell syntax highlighting., command: > 'ls' | create-highlight-command, result: "ls" | nu-highlight | print}]                                                                                                                                                                                                                                                                                                                                                                                               | # Generate a command to highlight code using Nushell syntax highlighting.
#: # > 'ls' | create-highlight-command
#: # "ls" | nu-highlight | print
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
#: | remove-comments-plus                | Trim comments and extra whitespaces from code blocks for use in the generated script.                                                                                                                                                                                                                                               | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Trim comments and extra whitespaces from code blocks for use in the generated script.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
#: | get-last-span                       | Extract the last span from a command to determine if `| print` can be appended                                                                                                                                                                                                                                                      | [{annotation: , command: > get-last-span 'let a = 1..10; $a | length', result: length}, {annotation: , command: > get-last-span 'let a = 1..10; let b = $a | length', result: let b = $a | length}, {annotation: , command: > get-last-span 'let a = 1..10; ($a | length);', result: let a = 1..10; ($a | length);}, {annotation: , command: > get-last-span 'let a = 1..10; ($a | length)', result: ($a | length)}, {annotation: , command: > get-last-span 'let a = 1..10', result: let a = 1..10}, {annotation: , command: > get-last-span '"abc"', result: "abc"}] | # Extract the last span from a command to determine if `| print` can be appended
#: #
#: # > get-last-span 'let a = 1..10; $a | length'
#: # length
#: #
#: # > get-last-span 'let a = 1..10; let b = $a | length'
#: # let b = $a | length
#: #
#: # > get-last-span 'let a = 1..10; ($a | length);'
#: # let a = 1..10; ($a | length);
#: #
#: # > get-last-span 'let a = 1..10; ($a | length)'
#: # ($a | length)
#: #
#: # > get-last-span 'let a = 1..10'
#: # let a = 1..10
#: #
#: # > get-last-span '"abc"'
#: # "abc"
#:                                                                                                                                                                                                                                |
#: | check-print-append                  | Check if the last span of the input ends with a semicolon or contains certain keywords to determine if appending ` | print` is possible.                                                                                                                                                                                            | [{annotation: , command: > check-print-append 'let a = ls', result: false}, {annotation: , command: > check-print-append 'ls', result: true}, {annotation: , command: > check-print-append 'mut a = 1; $a = 2', result: false}]                                                                                                                                                                                                                                                                                                                                        | # Check if the last span of the input ends with a semicolon or contains certain keywords to determine if appending ` | print` is possible.
#: #
#: # > check-print-append 'let a = ls'
#: # false
#: #
#: # > check-print-append 'ls'
#: # true
#: #
#: # > check-print-append 'mut a = 1; $a = 2'
#: # false
#:                                                                                                                                                                                                                                                                                                                                                                                                                      |
#: | create-indented-output              | Generate indented output for better visual formatting.                                                                                                                                                                                                                                                                              | [{annotation: , command: > 'ls' | create-indented-output, result: ls | table | lines | each {$'//  ($in)' | str trim --right} | str join (char nl)}]                                                                                                                                                                                                                                                                                                                                                                                                                   | # Generate indented output for better visual formatting.
#: #
#: # > 'ls' | create-indented-output
#: # ls | table | lines | each {$'//  ($in)' | str trim --right} | str join (char nl)
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | generate-print-statement            | Generate a print statement for capturing command output.                                                                                                                                                                                                                                                                            | [{annotation: , command: > 'ls' | generate-print-statement, result: ls | table | print; print ''}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Generate a print statement for capturing command output.
#: #
#: # > 'ls' | generate-print-statement
#: # ls | table | print; print ''
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | generate-table-statement            | Generate a table statement with optional width specification.                                                                                                                                                                                                                                                                       | [{annotation: , command: > 'ls' | generate-table-statement, result: ls | table}, {annotation: , command: > $env.numd.table-width = 10; 'ls' | generate-table-statement, result: ls | table --width 10}]                                                                                                                                                                                                                                                                                                                                                                | # Generate a table statement with optional width specification.
#: #
#: # > 'ls' | generate-table-statement
#: # ls | table
#: #
#: # > $env.numd.table-width = 10; 'ls' | generate-table-statement
#: # ls | table --width 10
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
#: | create-catch-error-current-instance | Generate a try-catch block to handle errors in the current Nushell instance.                                                                                                                                                                                                                                                        | [{annotation: , command: > 'ls' | create-catch-error-current-instance, result: try {ls} catch {|error| $error}}]                                                                                                                                                                                                                                                                                                                                                                                                                                                       | # Generate a try-catch block to handle errors in the current Nushell instance.
#: #
#: # > 'ls' | create-catch-error-current-instance
#: # try {ls} catch {|error| $error}
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#: | create-catch-error-outside          | Execute the command outside to obtain a formatted error message if any.                                                                                                                                                                                                                                                             | [{annotation: , command: > 'ls' | create-catch-error-outside, result: /Users/user/.cargo/bin/nu -c "ls" | complete | if ($in.exit_code != 0) {get stderr} else {get stdout}}]                                                                                                                                                                                                                                                                                                                                                                                          | # Execute the command outside to obtain a formatted error message if any.
#: #
#: # > 'ls' | create-catch-error-outside
#: # /Users/user/.cargo/bin/nu -c "ls" | complete | if ($in.exit_code != 0) {get stderr} else {get stdout}
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
#: | create-fence-output                 | Generate a fenced code block for output with a specific format.                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Generate a fenced code block for output with a specific format.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
#: | generate-print-lines                |                                                                                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | generate-tags                       |                                                                                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | extract-fence-options               | Parse options from a code fence and return them as a list.                                                                                                                                                                                                                                                                          | [{annotation: , command: > '```nu no-run, t' | extract-fence-options, result: ╭───┬────────╮
#: │ 0 │ no-run │
#: │ 1 │ try    │
#: ╰───┴────────╯}]                                                                                                                                                                                                                                                                                                                                                        | # Parse options from a code fence and return them as a list.
#: #
#: # > '```nu no-run, t' | extract-fence-options
#: # ╭───┬────────╮
#: # │ 0 │ no-run │
#: # │ 1 │ try    │
#: # ╰───┴────────╯
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
#: | modify-path                         | Modify a path by adding a prefix, suffix, extension, or parent directory.                                                                                                                                                                                                                                                           | [{annotation: , command: > 'numd/capture.nu' | modify-path --extension '.md' --prefix 'pref_' --suffix '_suf' --parent_dir abc, result: numd/abc/pref_capture_suf.nu.md}]                                                                                                                                                                                                                                                                                                                                                                                              | # Modify a path by adding a prefix, suffix, extension, or parent directory.
#: #
#: # > 'numd/capture.nu' | modify-path --extension '.md' --prefix 'pref_' --suffix '_suf' --parent_dir abc
#: # numd/abc/pref_capture_suf.nu.md
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
#: | create-file-backup                  | Create a backup of a file by moving it to a specified directory with a timestamp.                                                                                                                                                                                                                                                   | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Create a backup of a file by moving it to a specified directory with a timestamp.
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
#: | load-config                         |                                                                                                                                                                                                                                                                                                                                     | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
#: | generate-timestamp                  | Generate a timestamp string in the format YYYYMMDD_HHMMSS.                                                                                                                                                                                                                                                                          | [{annotation: , command: > generate-timestamp, result: 20241128_222140}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | # Generate a timestamp string in the format YYYYMMDD_HHMMSS.
#: #
#: # > generate-timestamp
#: # 20241128_222140
#:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
#: | scan                                | Returns a list of intermediate steps performed by `reduce`
#: (`fold`). It takes two arguments, an initial value to seed the
#: initial state and a closure that takes two arguments, the first
#: being the list element in the current iteration and the second
#: the internal state.
#: The internal state is also provided as pipeline input. | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | # Returns a list of intermediate steps performed by `reduce`
#: # (`fold`). It takes two arguments, an initial value to seed the
#: # initial state and a closure that takes two arguments, the first
#: # being the list element in the current iteration and the second
#: # the internal state.
#: # The internal state is also provided as pipeline input.
#: #
#: # # Example
#: # ```
#: # use std ["assert equal" "iter scan"]
#: # let scanned = ([1 2 3] | iter scan 0 {|x, y| $x + $y})
#: #
#: # assert equal $scanned [0, 1, 3, 6]
#: #
#: # # use the --noinit(-n) flag to remove the initial value from
#: # # the final result
#: # let scanned = ([1 2 3] | iter scan 0 {|x, y| $x + $y} -n)
#: #
#: # assert equal $scanned [1, 3, 6]
#: # ```
#:  |
